### ISSUE TITLE
Valid password characters can break sequelize connection string

### ISSUE THREAD

**Issue by Alfredo-Delgado** [feathersjs/generator-feathers#388] opened 2018-08-13 13:24 UTC
Moving to the appropriate repo: https://github.com/feathersjs-ecosystem/feathers-sequelize/issues/229

**Comment by daffl** [comment] 2018-08-18 19:40
Closing this as a duplicate of https://github.com/feathersjs/feathers/issues/676 but we can continue the discussion in the PR at https://github.com/feathersjs/generator-feathers/pull/389

**Closed by daffl** 2018-08-18 19:40 UTC
