### ISSUE TITLE
Generated sequelize.js should not modify app.setup

### ISSUE THREAD

**Issue by steve-kaufman** [feathersjs/generator-feathers#537] opened 2020-04-22 03:48 UTC
The sequelize.js module generated by the feathers cli modifies the app.setup method to include setting up the database relations followed by the `sequelize.sync()` call:

    const oldSetup = app.setup

    app.set('sequelizeClient', sequelize)

    app.setup = function (...args) {
      const result = oldSetup.apply(this, args)

      // Set up data relationships
      const models = sequelize.models
      Object.keys(models).forEach(name => {
        if ('associate' in models[name]) {
          models[name].associate(models)
        }
      })

      // Sync to the database
      app.set('sequelizeSync', sequelize.sync())

      return result
    }

Apart from this being somewhat convoluted, it raises problems when testing. Most of the documentation surrounding unit testing assumes that the backend is NeDB, and I found virtually no resources explaining how to go about testing services with any other backend.

The issue here is that `sequelize.sync` is quite the misnomer, as it is in fact an asynchronous method. If I'm using a sequelize backend (which I am), and I want to test a service (which I do), then I need to manually call `app.setup()` (to create the associations) and then `await app.get('sequelizeClient').sync()`, otherwise the tables may be undefined (assuming the testing database is separate from the development/production database). What's more is that `app.setup()` calls `sequelize.sync` itself, but it simply doesn't await it, rendering it ineffective in a testing environment where I want to immediately make calls to the services, and I end up calling `sequlize.sync` twice.

Now the workaround is simple. I just commented out the line in sequelize.js that calls `sequelize.sync`, and I add my `app.setup()` and `await app.get('sequelizeClient').sync()` to a beforeAll in my test suite. However, it was annoyingly difficult to figure out why the tables were nonexistent, and I'm a little surprised that the documentation largely ignores sequelize. 

I would love to see the documentation for testing extended to include examples with other database adapters, but in the meantime I think it would be good to rethink how app.setup is oddly just rewritten here.

* Using @feathersjs/cli version 4.3.0

**Comment by daffl** [comment] 2020-04-22 15:40
Duplicate of https://github.com/feathersjs/cli/issues/225 (where I already replied).

**Closed by daffl** 2020-04-22 15:40 UTC
