### ISSUE TITLE
Error running `yo feathers`

### ISSUE THREAD

**Issue by TrySpace** [feathersjs/generator-feathers#51] opened 2016-02-23 14:08 UTC
When I run `yo feathers`, after it creates all files, an error about installing packages occurs:

```
npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "feathers" "feathers-hooks" "feathers-errors" "feathers-configuration" "serve-favicon" "compression" "winston" "body-parser" "feathers-rest" "feathers-socketio" "cors" "feathers-authentication" "passport" "mongoose" "feathers-mongoose" "--save"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.3
npm ERR! code ENOSELF

```

also:
```
npm ERR! Refusing to install feathers as a dependency of itself
```

I'm pretty sure I have the latest versions of npm. 

The `npm-debug.log` is also not helpful

**Comment by daffl** [comment] 2016-02-23 15:19
As the errors says, it looks like you are trying to install Feathers into it's own folder (potentially a subfolder of the cloned repository). I just tried on Ubuntu and everything worked as expected.

**Comment by ekryski** [comment] 2016-02-23 15:42
@TrySpace which versions of yo, npm, and node are you running?

**Comment by ekryski** [comment] 2016-02-24 22:59
I can't reproduce this. I've run the generator multiple times today on multiple node versions and it's worked fine. I think it might be your environment @TrySpace. We recommend using nvm and node v5.0+. I'm going to close this. Please report back if you get it working or not and we can re-open if it's still an issue.

**Closed by ekryski** 2016-02-24 22:59 UTC
