### ISSUE TITLE
Can't choose "remove" in hook generator

### ISSUE THREAD

**Issue by willkessler** [feathersjs/generator-feathers#82] opened 2016-03-19 00:23 UTC
![image](https://cloud.githubusercontent.com/assets/176268/13895226/0ec26f6c-ed2e-11e5-8e97-e1e3d3000be5.png)

you cannot choose "remove" so you have to add these manually.

To reproduce simply run through the tutorial (sample chat app) and try

`yo feathers:hook`

**Comment by ekryski** [comment] 2016-03-19 02:07
Hmm. I can't reproduce. I am able to see it and select/deselect it by hitting spacebar. Maybe it is a terminal height issue? Anyone else able to reproduce this?

<img width="455" alt="screen shot 2016-03-18 at 8 06 02 pm" src="https://cloud.githubusercontent.com/assets/599019/13896059/e854d33a-ed44-11e5-8bcb-0be177953133.png">

**Comment by daffl** [comment] 2016-03-21 02:06
@willkessler What are your terminal line number settings? If it doesn't let you scroll down then we might escalate this as a Yeoman or Inquirer bug.

**Comment by ekryski** [comment] 2016-03-21 16:38
Ok going to close this for now. If it comes up again or @willkessler is still having issues then we can re-open.

**Closed by ekryski** 2016-03-21 16:38 UTC
